In [68]:
import pandas as pd
import numpy as np
from datetime import datetime

### Load the file students.csv

In [69]:
data = pd.read_csv("students.csv")

### Make sure Score Date is parsed as datetime

In [70]:
datetime.strptime("2/28/2025", "%m/%d/%Y")

datetime.datetime(2025, 2, 28, 0, 0)

### Print DataFrame shape

In [71]:
print("DataFrame Shape is:", data.shape)

DataFrame Shape is: (9, 8)

### Print Column List

In [72]:
print("Columns of DataFrame:")
for i in list(data.columns):
    print(i, end=", ")

Columns of DataFrame:
Student ID, Name, Age, Grade, Subject, City, Passed, Score Date,

### Print Data Types

In [73]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student ID  9 non-null      int64
 1   Name        9 non-null      object
 2   Age         9 non-null      int64
 3   Grade       8 non-null      float64
 4   Subject     9 non-null      object
 5   City        9 non-null      object
 6   Passed      9 non-null      bool
 7   Score Date  8 non-null      object
dtypes: bool(1), float64(1), int64(2), object(4)
memory usage: 641.0+ bytes

### Show first 7 rows

In [74]:
data.head(7)

   Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True  1/15/2025
1           2    Sara   32   92.0    Physics  Alexandria    True  2/10/2025
2           3    Omar   19   65.0       Math        Giza   False  1/20/2025
3           4    Lina   28   78.0  Chemistry       Cairo    True   3/5/2025
4           5  Khaled   45   55.0    Physics    Mansoura   False  2/28/2025
5           6    Nour   22    NaN    English  Alexandria    True  1/10/2025
6           7    Yara   30   89.0       Math       Cairo    True        NaN

### Show last 3 rows

In [75]:
data.tail(3)

   Student ID     Name  Age  Grade    Subject   City  Passed Score Date
6           7     Yara   30   89.0       Math  Cairo    True        NaN
7           8  Mohamed   27   72.0  Chemistry   Giza    True  3/12/2025
8           8  Mohamed   27   72.0  Chemistry   Giza    True  3/12/2025

### Show how many null values

In [76]:
data.isna().sum()

Student ID    0
Name          0
Age           0
Grade         1
Subject       0
City          0
Passed        0
Score Date    1
dtype: int64

### What is the average, minimum, and maximum Grade?

In [77]:
print("Average Grade:", data['Grade'].mean(skipna=True), end="\n\n")
print("Minimum Grade:", data['Grade'].min(skipna=True), end="\n\n")
print("Maximum Grade:", data['Grade'].max(skipna=True))

Average Grade: 76.375

Minimum Grade: 55.0

Maximum Grade: 92.0

### How many unique cities are there?

In [78]:
for i in data['City'].unique():
    print(i)

Cairo
Alexandria
Giza
Mansoura

### Use value_counts() to show how many students per Subject.

In [79]:
data['Subject'].value_counts()

Subject
Math         3
Chemistry    3
Physics      2
English      1
Name: count, dtype: int64

### Select only the columns: Name, Grade, Subject, City.

In [80]:
data[["Name", "Grade", "Subject", "City"]]

      Name  Grade    Subject        City
0    Ahmed   88.0       Math       Cairo
1     Sara   92.0    Physics  Alexandria
2     Omar   65.0       Math        Giza
3     Lina   78.0  Chemistry       Cairo
4   Khaled   55.0    Physics    Mansoura
5     Nour    NaN    English  Alexandria
6     Yara   89.0       Math       Cairo
7  Mohamed   72.0  Chemistry        Giza
8  Mohamed   72.0  Chemistry        Giza

### Show all students who Passed and have Grade ≥ 85.

In [81]:
data[data['Grade'] >= 85]

   Student ID   Name  Age  Grade  Subject        City  Passed Score Date
0           1  Ahmed   25   88.0     Math       Cairo    True  1/15/2025
1           2   Sara   32   92.0  Physics  Alexandria    True  2/10/2025
6           7   Yara   30   89.0     Math       Cairo    True        NaN

### Show students whose Name contains the letter "a" or "A" (case insensitive).

In [82]:
data[data['Name'].apply(lambda x: True if x[0].lower() == 'a' else False)]

   Student ID   Name  Age  Grade Subject   City  Passed Score Date
0           1  Ahmed   25   88.0    Math  Cairo    True  1/15/2025

### Show students in Cairo or Alexandria with Grade < 80.

In [83]:
data[(data['City'] == 'Cairo') & (data['Grade'] < 80)]

   Student ID  Name  Age  Grade    Subject   City  Passed Score Date
3           4  Lina   28   78.0  Chemistry  Cairo    True   3/5/2025

### Show students with Grade between 80 and 90 (inclusive).

In [84]:
data[(data['Grade'] >= 80) & (data['Grade'] <= 90)]

   Student ID   Name  Age  Grade Subject   City  Passed Score Date
0           1  Ahmed   25   88.0    Math  Cairo    True  1/15/2025
6           7   Yara   30   89.0    Math  Cairo    True        NaN

### Using .loc, change Khaled's grade from 55 to 68.

In [ ]:
data.loc[data['Name'] == 'Khaled', 'Grade'] = 68

In [87]:
data[data['Name'] == 'Khaled']

   Student ID    Name  Age  Grade  Subject      City  Passed Score Date
4           5  Khaled   45   68.0  Physics  Mansoura   False  2/28/2025

### Add a new column Is_Excellent that is True if Grade ≥ 90, False otherwise (vectorized)

In [88]:
data['Is_Excellent'] = data['Grade'] >= 90

In [89]:
data

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True
2,3,Omar,19,65.0,Math,Giza,False,1/20/2025,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2/28/2025,False
5,6,Nour,22,NaN,English,Alexandria,True,1/10/2025,False
6,7,Yara,30,89.0,Math,Cairo,True,NaN,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False

### Fill missing Grade values with the average Grade.

In [90]:
data['Grade'].fillna(data['Grade'].mean(skipna=True), inplace=True)

In [91]:
data

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True
2,3,Omar,19,65.0,Math,Giza,False,1/20/2025,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2/28/2025,False
5,6,Nour,22,78.0,English,Alexandria,True,1/10/2025,False
6,7,Yara,30,89.0,Math,Cairo,True,NaN,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False

### Fill missing Score Date values with the most common date (mode).

In [96]:
mode_value = data['Score Date'].mode()[0]

data['Score Date'] = data['Score Date'].fillna(mode_value)

In [97]:
data

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent
0,1,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False
1,2,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True
2,3,Omar,19,65.0,Math,Giza,False,1/20/2025,False
3,4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False
4,5,Khaled,45,68.0,Physics,Mansoura,False,2/28/2025,False
5,6,Nour,22,78.0,English,Alexandria,True,1/10/2025,False
6,7,Yara,30,89.0,Math,Cairo,True,3/12/2025,False
7,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False
8,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False

### Create a column Grade_Category using pd.cut with bins.

In [98]:
data['Grade_Category'] = pd.cut(data['Grade'], bins=[0, 69, 79, 89, 100], labels=["Fail", "Average", "Good", "Excellent"])

In [99]:
data

,Student ID,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Grade_Category
0,1,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,Good
1,2,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,Excellent
2,3,Omar,19,65.0,Math,Giza,False,1/20/2025,False,Fail
3,4,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,Average
4,5,Khaled,45,68.0,Physics,Mansoura,False,2/28/2025,False,Fail
5,6,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,Average
6,7,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,Good
7,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average
8,8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average

### Remove the column Student ID.

In [102]:
data.drop(columns="Student ID", inplace=True)

In [103]:
data

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Grade_Category
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,Good
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,Excellent
2,Omar,19,65.0,Math,Giza,False,1/20/2025,False,Fail
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,Average
4,Khaled,45,68.0,Physics,Mansoura,False,2/28/2025,False,Fail
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,Average
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,Good
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average

### Keep only students who Passed.

In [104]:
data_passed = data[data['Grade_Category'] != "Fail"]

In [105]:
data_passed

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Grade_Category
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,Good
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,Excellent
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,Average
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,Average
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,Good
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average

### Sort the DataFrame by Grade descending.

In [111]:
data_passed.sort_values(by="Grade", ascending=False, inplace=True)
data_passed

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Grade_Category
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,Excellent
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,Good
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,Good
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,Average
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,Average
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average

In [114]:
data_passed = data_passed.sort_values(by=['City', 'Grade'], ascending=[True, False])
data_passed

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Grade_Category
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,Excellent
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,Average
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,Good
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,Good
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,Average
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average

### Add a column Rank that ranks students by Grade

In [117]:
data_passed['Rank'] = data['Grade'].rank(ascending=False, method='min').astype(int)

In [118]:
data_passed

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Grade_Category,Rank
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,Excellent,1
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,Average,4
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,Good,2
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,Good,3
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,Average,4
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average,6
8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average,6

### Show the top 4 students with the highest grades.

In [121]:
data_passed.nlargest(columns='Grade', n=4)

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Grade_Category,Rank
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,Excellent,1
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,Good,2
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,Good,3
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,Average,4

### Show the 3 youngest students.

In [122]:
data_passed.nsmallest(columns='Age', n=3)

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Grade_Category,Rank
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,Average,4
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,Good,3
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average,6

### Find the student(s) with the highest Grade and show their Name and Grade.

In [123]:
max_grade = data['Grade'].max()

data_passed[data_passed['Grade'] == max_grade]

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Grade_Category,Rank
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,Excellent,1

### After filling missing grades, recalculate the average Grade per Subject.

In [ ]:
print("Average Grade:", data['Grade'].mean(), end="")

Average Grade: 78.0

### Create a new column City_Avg that shows the average grade of each student's city.

In [127]:
data_passed['City_Avg'] = data_passed.groupby('City')['Grade'].transform('mean')

In [128]:
data_passed

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Grade_Category,Rank,City_Avg
1,Sara,32,92.0,Physics,Alexandria,True,2/10/2025,True,Excellent,1,85.0
5,Nour,22,78.0,English,Alexandria,True,1/10/2025,False,Average,4,85.0
6,Yara,30,89.0,Math,Cairo,True,3/12/2025,False,Good,2,85.0
0,Ahmed,25,88.0,Math,Cairo,True,1/15/2025,False,Good,3,85.0
3,Lina,28,78.0,Chemistry,Cairo,True,3/5/2025,False,Average,4,85.0
7,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average,6,72.0
8,Mohamed,27,72.0,Chemistry,Giza,True,3/12/2025,False,Average,6,72.0

### Show the subject with the highest average grade.

In [129]:
subject_averages = data.groupby('Subject')['Grade'].mean()

best_subject = subject_averages.idxmax()
highest_score = subject_averages.max()

print(f"The highest performing subject is {best_subject} with an average of {highest_score:.2f}")

The highest performing subject is Math with an average of 80.67